# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: teampikachu08
service: brian-kwong-express-sl

plugins:
  - "serverless-offline"

build:
  esbuild:
    bundle: true
    minify: true
    # Adds support for legacy CommonJS modules in ESM projects
    banner:
      js: |
        import { createRequire } from 'module';
        const require = createRequire(import.meta.url);

provider:
  name: aws
  runtime: nodejs24.x
  environment: ${file(./env.js):env}
  httpApi:
    cors: true

functions:
  api:
    handler: src/index.handler
    url: true
    events:
      - httpApi: "*"

package:
  patterns:
    - "src/data/bkwong_cv.md"
